mode: train
graph_type: not_very_hetero
load_graph: "not_very_hetero_12m.pt"
model_type: flightgnn
epochs: 100
lr: 0.001
weight_decay: 0.0001
batch_size: 40000
neighbor_sampling: true
neighbor_fanouts: "20,15,10"
criterion: huber
verbosity: 1
