config: null
mode: train
rows: null
graph_type: hetero3
save_graph: hetero3_reg_graph
load_graph: hetero3_reg_graph
time_window: 6
model_type: hgt
data_path: data/datasets/
graph_dir: pretrained/graphs/
model_dir: pretrained/models/
log_dir: logs/
model_file: hetero3_hgt_reg
criterion: huber
amp: false
compile: false
compile_backend: inductor
compile_mode: default
resume: false
epochs: 500
lr: 0.00001
weight_decay: 0.000001
prediction_type: regression
batch_size: 800000
neighbor_sampling: true
neighbor_fanouts: "15,10"
border: 0.6
verbosity: 1
