config: null
mode: train
rows: null
graph_type: hetero1
save_graph: hetero1_rgcn_classification_graph.pt
load_graph: hetero1_rgcn_classification_graph.pt
time_window: 6
model_type: rgcn
data_path: data/datasets/
graph_dir: pretrained/graphs/
model_dir: pretrained/models/
log_dir: logs/
model_file: hetero1_rgcn_classification
criterion: huber
amp: false
compile: false
compile_backend: inductor
compile_mode: default
resume: false
epochs: 500
lr: 0.001
weight_decay: 0.000001
prediction_type: classification
batch_size: 150000
neighbor_sampling: true
neighbor_fanouts: "15,10"
border: 0.45
verbosity: 1
