mode: train
verbosity: 1
rows: null

# Data
data_path: data/datasets/
data_split: [80, 10, 10]
normalize: true

# Graph
graph_type: hetero1
save_graph: hetero1_class_graph
load_graph: hetero1_class_graph

# Model
model_type: hgt
prediction_type: classification
model_file: hetero1_hgt_class
border: 0.6

# Training
epochs: 500
lr: 0.00001
weight_decay: 0.000001
batch_size: 800000
criterion: huber

# Neighbor Sampling
neighbor_sampling: true
neighbor_fanouts: "15,10"

# Performance
amp: false
compile: false
compile_backend: inductor
compile_mode: default
resume: false

# Directories
graph_dir: pretrained/graphs/
model_dir: pretrained/models/
log_dir: logs/
