config: null
mode: train
rows: null
graph_type: homo
save_graph: homo_class_graph
load_graph: homo_class_graph
time_window: 6
model_type: hgt
data_path: data/datasets/
graph_dir: pretrained/graphs/
model_dir: pretrained/models/
log_dir: logs/
model_file: homo_hgt_class
criterion: huber
amp: false
compile: false
compile_backend: inductor
compile_mode: default
resume: false
epochs: 100
lr: 0.001
weight_decay: 0.000001
prediction_type: classification
batch_size: 300000
neighbor_sampling: true
neighbor_fanouts: "15,10"
border: 0.6
verbosity: 1
