mode: train
rows: null
graph_type: homo
save_graph: homo_graph
load_graph: homo_graph
model_type: rgcn
data_path: data/datasets/
data_split: [80, 10, 10]
normalize: true
use_sliding_windows: false

graph_dir: pretrained/graphs/
model_dir: pretrained/models/
log_dir: logs/
model_file: homo_rgcn_reg
criterion: huber
amp: false
compile: false
compile_backend: inductor
compile_mode: default
resume: false
epochs: 200
lr: 0.00001
weight_decay: 0.000001
prediction_type: regression
batch_size: 800000
neighbor_sampling: true
neighbor_fanouts: "15,10"
border: 0.6
verbosity: 1
