mode: train
graph_type: not_very_hetero
save_graph: ""
load_graph: "not_very_hetero_12m.pt"
model_file: rgcn_not_very_hetero_12m
model_type: rgcn
data_path: data/datasets/12M_20251213_112224.csv
epochs: 100
lr: 0.0005
weight_decay: 0.0001
batch_size: 500000
neighbor_sampling: true
neighbor_fanouts: "20,15"
criterion: huber
verbosity: 1
