# Example config file, it trains a RGCN without sampling. It loads the graph from disk.
# This config demands ~6700MB of VRAM. Other settings match defaults.
mode: train
rows: null
graph_type: hetero1
save_graph: ""
load_graph: "hetero1_4m.pt"
model_type: rgcn
data_path: data/datasets/
graph_dir: src/graph/
model_dir: src/models/
epochs: 50
lr: 0.001
prediction_type: regression
batch_size: 500000
neighbor_sampling: false
neighbor_fanouts: "30,20"
verbosity: 1
