# Example config file, it trains a RGCN with sampling
# It loads the graph from disk, then samples it with batch size 500k and fanout 30,20; 
# This config demands ~6000MB of VRAM. Other settings match defaults.
mode: train
rows: null
graph_type: hetero1
save_graph: ""
load_graph: "hetero1_12m.pt"
model_type: rgcn
model_file: rgcn_hetero1_12m_e100lr05
data_path: data/datasets/
graph_dir: src/graph/
model_dir: src/models/
epochs: 100
lr: 0.0005
prediction_type: regression
batch_size: 600000
neighbor_sampling: true
neighbor_fanouts: "30,20"
verbosity: 1
