# Example config file, it trains a RGCN with sampling. It loads the graph from disk.
# This config demands ~6850MB of VRAM. Other settings match defaults.
mode: train
rows: null
graph_type: heteroNew3
save_graph: ""
load_graph: "new3_12m.pt"
model_file: rgcnmodel_new3_12m
model_type: rgcnmodel
data_path: data/datasets/12M_20251213_112224.csv
graph_dir: src/graph/
model_dir: src/models/
epochs: 100
lr: 0.001
prediction_type: regression
batch_size: 300000
neighbor_sampling: true
neighbor_fanouts: "15,10"
verbosity: 1
