# Example config file, it trains a RGCN with sampling
# It loads the graph from disk, then samples it with batch size 500k and fanout 30,20; 
# This config demands ~6600MB of VRAM. Other settings match defaults.
mode: train
development: false
graph_type: base
save_graph: ""
load_graph: "base4m.pt"
model_type: rgcn
data_path: data/datasets/
graph_dir: src/graph/
model_dir: src/models/
epochs: 50
lr: 0.001
prediction_type: regression
batch_size: 500000
neighbor_sampling: false
neighbor_fanouts: "30,20"
verbosity: 1
