# Example config file, it trains a RGCN without sampling. It loads the graph from disk.
# This config demands ~6700MB of VRAM. Other settings match defaults.
mode: train
rows: null
graph_type: hetero2
save_graph: ""
load_graph: "hetero3_1m_class.pt"
model_file: rgcn_hetero3_1m_class
model_type: rgcn
data_path: data/datasets/1M_20251219_003528.csv
graph_dir: src/graph/
model_dir: src/models/
epochs: 50
lr: 0.01
border: 0.6
prediction_type: classification
batch_size: 500000
neighbor_sampling: false
neighbor_fanouts: "30,20"
verbosity: 1
